title: Shazam Design System
description: A proposal for a Shazam design system.
theme: just-the-docs

url: https://asiakostrzewa/ShazamDesignSystem

aux_links:
  Template Repository: https://github.com/asiakostrzewa/ShazamDesignSystem

callouts_level: quiet
callouts:
  good:
    title: DO
    color: green
  warning:
    title: DON'T
    color: red