title: Shazam Design System project
description: A proposal for a Shazam design system.
theme: just-the-docs

url: https://asiakostrzewa/ShazamDesignSystem

aux_links:
  Template Repository: https://github.com/asiakostrzewa/ShazamDesignSystem
