title: Shazam Design System
description: A proposal for a Shazam design system.
theme: just-the-docs
color_scheme: css

url: https://asiakostrzewa/ShazamDesignSystem

# Logo
logo: "/links/Shazam_blue.png"

#Favicon
favicon_ico: "/links/Shazam_blue.png"

callouts_level: quiet
callouts:
  note:
    title: NOTE
    color: blue
  good:
    title: DO
    color: green
  warning:
    title: DON'T
    color: red

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2024 Joanna Kostrzewa. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"